version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      ## https://crontab.guru/#0_0_*_*_2
      cronjob: "0 0 * * 2"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      ## https://crontab.guru/#0_0_*_*_2
      cronjob: "0 0 * * 2"
