pull_request_rules:
  - name: Label queued pull requests
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - mergify/queued
  - name: Label conflicting pull requests
    description: Toggle the conflict label when got conflicted
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - status/conflict
  - name: Label drafting pull requests
    description: Toggle the draft label when got drafted
    conditions:
      - draft
      - -closed
    actions:
      label:
        toggle:
          - status/draft
  - name: Queue the maintainer pull requests
    description: Automatically queue maintainer pull requests
    conditions:
      - -draft
      - -closed
      - -conflict
      - author=kamontat
    actions:
      queue:
  - name: Ask for review the dependabot pull requests
    description: Automatically ask maintainer to review dependabot pull requests
    conditions:
      - -draft
      - -closed
      - -conflict
      - author=dependabot[bot]
    actions:
      request_reviews:
        users:
          - kamontat
  - name: Queue the dependabot pull requests
    description: Automatically queue dependabot pull requests when reviewed
    conditions:
      - -draft
      - -closed
      - -conflict
      - author=dependabot[bot]
      - approved-reviews-by=kamontat
    actions:
      queue:
  - name: Queue the contributors pull requests
    description: Queue contributors pull requests when reviewed
    conditions:
      - -draft
      - -closed
      - -conflict
      - approved-reviews-by=kamontat
    actions:
      queue:

queue_rules:
  - name: default
    merge_method: squash
    update_method: rebase
    branch_protection_injection_mode: queue
