pull_request_rules:
  - name: Label queued pull requests
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - mergify/queued
  - name: Label conflicting pull requests
    description: Toggle the conflict label when got conflicted
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - status/conflict
  - name: Label drafting pull requests
    description: Toggle the draft label when got drafted
    conditions:
      - draft
      - -closed
    actions:
      label:
        toggle:
          - status/draft
  - name: Queue the pull requests for maintainers
    description: Queue pull requests when CI is success
    conditions:
      - -draft
      - -closed
      - -conflict
      - author=kamontat
      - check-success=main
    actions:
      queue:
  - name: Queue the pull requests for contributors
    description: Queue pull requests when CI is success and reviewed
    conditions:
      - -draft
      - -closed
      - -conflict
      - approved-reviews-by=kamontat
      - check-success=main
    actions:
      queue:

queue_rules:
  - name: default
    merge_method: squash
    update_method: rebase
    branch_protection_injection_mode: queue
